---
title: "Mortgage Interest Rates"
subtitle: "Skandia Bank"
author: "Roy Francis"
date: today
date-format: "DD-MMM-YYYY"
title-block-banner: true
format: 
  html:
    page-layout: full
    self-contained: true
    theme: lux
---

```{r,include=FALSE}
library(lubridate)
library(readxl)
library(highcharter)
library(tidyr)
library(dplyr)

key_a <- c(y0.5 = "3 months", y1 = "1 year", y2 = "2 years", y3 = "3 years", y5 = "5 years")
key_b <- c(y0.5 = 1, y1 = 2, y2 = 3, y3 = 4, y5 = 5)

s <- readxl::read_xlsx("skandia-interest.xlsx") %>%
  tidyr::pivot_longer(`y0.5`:`y5`, names_to = "period", values_to = "value") %>%
  mutate(year = as.character(year)) %>%
  mutate(label = factor(recode(period, !!!key_a), levels = key_a)) %>%
  mutate(ord = recode(period, !!!key_b)) %>%
  mutate(date = as_date(lubridate::dmy(paste0("28-", month, "-", year), tz = "Europe/Stockholm"))) %>%
  arrange(ord, date)

s1 <- s %>%
  dplyr::select(-period, -label, -date) %>%
  dplyr::group_by(year, month) %>%
  tidyr::nest() %>%
  mutate(slope_5 = purrr::map(data, ~ coef(lm(value ~ ord, data = .x))[["ord"]])) %>%
  select(-data) %>%
  unnest(cols = slope_5) %>%
  mutate(date = as_date(lubridate::dmy(paste0("28-", month, "-", year), tz = "Europe/Stockholm"))) %>%
  ungroup()

s2 <- s %>%
  filter(period != "y5") %>%
  dplyr::select(-period, -label, -date) %>%
  dplyr::group_by(year, month) %>%
  tidyr::nest() %>%
  mutate(slope_3 = purrr::map(data, ~ coef(lm(value ~ ord, data = .x))[["ord"]])) %>%
  select(-data) %>%
  unnest(cols = slope_3) %>%
  mutate(date = as_date(lubridate::dmy(paste0("28-", month, "-", year), tz = "Europe/Stockholm"))) %>%
  ungroup()

s3 <- s %>%
  filter(period != "y5" & period != "y3") %>%
  dplyr::select(-period, -label, -date) %>%
  dplyr::group_by(year, month) %>%
  tidyr::nest() %>%
  mutate(slope_2 = purrr::map(data, ~ coef(lm(value ~ ord, data = .x))[["ord"]])) %>%
  select(-data) %>%
  unnest(cols = slope_2) %>%
  mutate(date = as_date(lubridate::dmy(paste0("28-", month, "-", year), tz = "Europe/Stockholm"))) %>%
  ungroup()

s4 <- s1 %>%
  inner_join(select(s2, date, slope_3), by = "date") %>%
  inner_join(select(s3, date, slope_2), by = "date") %>%
  tidyr::pivot_longer(c(slope_5, slope_3, slope_2), names_to = "period", values_to = "value") %>%
  arrange(date)
```

```{r}
#| echo: false
#| label: interest
#| fig-cap: Skandia interest rates for home loan over time. Average rate per month is shown. Different lines (colours) denotes different periods of fixed rates (3 months, 1 year, 2 years, 3 years, 5 years).

hchart(s,"line",hcaes(x=date,y=value,group=label)) %>%
  hc_xAxis(title=list(text="Date"),crosshair=TRUE) %>%
  hc_yAxis(title=list(text="Interest rate %"),crosshair=TRUE) %>%
  hc_chart(zoomType="xy") %>%
  hc_plotOptions(scatter=list(marker=list(radius=3),opacity=0.8)) %>%
  hc_legend(enabled=TRUE,verticalAlign="top",align="right") %>%
  hc_size(height=500) %>%
  #hc_title(text=title,align="left") %>%
  hc_exporting(buttons=list(contextButton=list(enabled=TRUE)))
```

```{r}
#| echo: false
#| label: interest-slope
#| fig-cap: Change (Slope) in fixed interest rates per month. Slope is computed over 3 months - 2 years (slope_2), 3 months - 3 years (slope_3) or 3 months - 5 years (slope_5).

hchart(s4,"line",hcaes(x=date,y=value,group=period)) %>%
  hc_xAxis(title=list(text="Date"),crosshair=TRUE) %>%
  hc_yAxis(title=list(text="Slope"),crosshair=TRUE) %>%
  hc_chart(zoomType="xy") %>%
  hc_plotOptions(scatter=list(marker=list(radius=3),opacity=0.8)) %>%
  hc_legend(enabled=TRUE,verticalAlign="top",align="right") %>%
  hc_size(height=450) %>%
  #hc_title(text=title,align="left") %>%
  hc_colors(c("#CA527D", "#8A81CA", "#70D451")) %>%
  hc_exporting(buttons=list(contextButton=list(enabled=TRUE)))
```

```{r}
#| echo: false
#| label: interest-ratio
#| fig-cap: Fold change (Log2 Ratio) of fixed interest rates relative to variable interest rate over time (1 year / 3 month, 2 year / 3 month, 3 year / 3 month and 5 year / 3 month ratios). Y axis value 0 can be considered as the reference (3 month rate) and other rates are relative to this.

s5 <- s %>%
  tidyr::pivot_wider(id_cols = c(date, year, month), names_from = "period", values_from = "value") %>%
  dplyr::arrange(date) %>%
  mutate("5y" = round(log2(y5 / y0.5), 3)) %>%
  mutate("3y" = round(log2(y3 / y0.5), 3)) %>%
  mutate("2y" = round(log2(y2 / y0.5), 3)) %>%
  mutate("1y" = round(log2(y1 / y0.5), 3)) %>%
  dplyr::select(date, `5y`, `3y`, `2y`, `1y`) %>%
  tidyr::pivot_longer(!date, names_to = "ratio", values_to = "value")

hchart(s5, "line", hcaes(x = date, y = value, group = ratio)) %>%
  hc_xAxis(title = list(text = "Date"), crosshair = TRUE) %>%
  hc_yAxis(title = list(text = "Fold change (Log2 Ratio)"), crosshair = TRUE) %>%
  hc_chart(zoomType = "xy") %>%
  hc_plotOptions(scatter = list(marker = list(radius = 3), opacity = 0.8)) %>%
  hc_legend(enabled = TRUE, verticalAlign = "top", align = "right") %>%
  hc_size(height = 450) %>%
  # hc_title(text=title,align="left") %>%
  hc_colors(c("#9FE2BF", "#CCCCFF", "#FFBF00", "#DE3163")) %>%
  hc_exporting(buttons = list(contextButton = list(enabled = TRUE)))
```

---

[Source: Skandia](https://www.skandia.se/lana/bolan/bolanerantor/snittrantor/)

